### ISSUE TITLE
legal terms not accepted

### ISSUE THREAD

**Issue by khushil** [PaloAltoNetworks/terraform-templates#14]
When trying to run this I get:

* azurerm_virtual_machine.PAN_FW_FW: 1 error(s) occurred:

* azurerm_virtual_machine.PAN_FW_FW: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ResourcePurchaseValidationFailed" Message="User failed validation to purchase resources. Error message: 'Legal terms have not been accepted for this item on this subscription. To accept legal terms using PowerShell, please use Get-AzureRmMarketplaceTerms and Set-AzureRmMarketplaceTerms API(https://go.microsoft.com/fwlink/?linkid=862451) or deploy via the Azure portal to accept the terms'"
* azurerm_virtual_machine_extension.PAN_FW_WEB_EXT_MIN: 1 error(s) occurred:

* azurerm_virtual_machine_extension.PAN_FW_WEB_EXT_MIN: azure#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded

Seems linked to https://github.com/terraform-providers/terraform-provider-azurerm/issues/1283

**Comment by vinayvenkat** [comment]
Hello @khushil 

Yes this is expected. The issue here is that when are trying to spin up a market place entity for the first time on Azure, you will always have to manually deploy and accept the Market Place Terms.  Once you have done that, you don't need to worry about it for all subsequent invocations and usage of the market place item. 
Hope this helps.
Thanks,

**Comment by MarcinKrupinski** [comment]
Hi @vinayvenkat,

could you clarify the approach that you suggested ? I had one firewall instance deployed manually (and I've signed the terms&conditions), and all the consecutives deployments via terraform were still failing with the error that @khushil raised in the beginning. Did you find out some alternative solution to this issue, that would make it work also for very first firewall deployment ?

Thanks in advance for help !
Marcin
