### ISSUE TITLE
AWS keys and secrets available in a customer facing file/repo

### ISSUE THREAD

**Issue by solalraveh** [PaloAltoNetworks/terraform-templates#26]
This file is publicly open and a customer reported he can see the AWS key and Secret in it:

https://github.com/PaloAltoNetworks/terraform-templates/blob/02e6431d7491762c43dea9fa9c735b9053c22da3/one-click-multi-cloud/one-click-aws/aws_creds.tf

And in this one:

https://github.com/wwce/terraform.git
linked from: https://live.paloaltonetworks.com/t5/AWS/ct-p/AWS

## Steps to reproduce

1.
2.
3.
4.

## Your Environment

- Version used:
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3):
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by vinayvenkat** [comment]
Thank you for bringing this to our attention! These keys have been decommissioned.
